image: registry.gitlab.com/jonashackt/aws-kubectl-tkn:0.21.0

.before_script_template:
  before_script:
    - mkdir ~/.kube
    - echo "$EKSKUBECONFIG" > ~/.kube/config
    - echo "--- Testdrive connection to cluster"
    - kubectl cluster-info
    - kubectl get nodes
    - echo "--- Test if Tekton pipelines are set up"
    - kubectl get pods --namespace tekton-pipelines
    - echo "--- Change permission for kubecfg"
    - chmod +x kubecfg

stages:
  - merge
  - deploy

merge-with-target:
  stage: merge
  variables:
    NAMESPACE_DIR: 'namespaces/"$GITLAB_USER_LOGIN"/*'
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - changes:
        - $NAMESPACE_DIR
  script:
    - echo "Files in namespaces directory changed"
    # - yum install -y -q git
    # - git diff-tree --name-only --no-commit-id -r $CI_MERGE_REQUEST_TARGET_BRANCH_SHA -r $CI_COMMIT_SHA


deploy-app:
  extends: .before_script_template
  stage: deploy
  rules:
    # Only run pipeline if the code is committed/ merged into the master branch 
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    # This will deploy into k8s cluster directly
    # - echo "--- Deploy nusfriends1 to k8s"
    # - ./kubecfg update nusfriends1.jsonnet

    # This will deploy into k8s cluster via Tekton Pipeline
    - echo "--- Deloy nusfriends to k8s via Tekton Pipeline"
    - ./kubecfg --ext-str "CI_COMMIT_SHA=$CI_COMMIT_SHA" update test_pipeline.jsonnet

    # Display logs from Tekton Pipeline
    # in nusfriends-1 namespace
    - echo "--- Show Tekton PipelineRun logs"
    - kubectl logs -n nusfriends-1 --selector=tekton.dev/pipelineRun=$CI_COMMIT_SHA -f --all-containers --max-log-requests=8 --pod-running-timeout=45s --previous=false --ignore-errors=true

    # Hardcoded show external IP 
    - echo "--- Your App is Running on IP ADDRESS..."
    - kubectl get services -n nusfriends-1 nus-jira-app-service --output jsonpath='{.status.loadBalancer.ingress[0].ip}'
