image: registry.gitlab.com/jonashackt/aws-kubectl-tkn:0.21.0

before_script:
  - mkdir ~/.kube
  - echo "$EKSKUBECONFIG" > ~/.kube/config
  - echo "--- Testdrive connection to cluster"
  - kubectl cluster-info
  - kubectl get nodes
  - echo "--- Test if Tekton pipelines are set up"
  - kubectl get pods --namespace tekton-pipelines
  - echo "--- Change permission for kubecfg"
  - chmod +x kubecfg

stages:
  - deploy

build-image:
  stage: deploy
  rules:
    # Only run pipeline if the code is committed/ merged into the master branch 
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    # This will deploy into k8s cluster directly
    # - echo "--- Deploy nusfriends1 to k8s"
    # - ./kubecfg update nusfriends1.jsonnet

    # This will deploy into k8s cluster via Tekton Pipeline
    - echo "--- Deloy nusfriends to k8s via Tekton Pipeline"
    - ./kubecfg --ext-str "CI_COMMIT_SHA=$CI_COMMIT_SHA" update test_pipeline.jsonnet

    # Display logs from Tekton Pipeline
    # in nusfriends-1 namespace
    - echo "--- Show Tekton PipelineRun logs"
    - kubectl logs -n nusfriends-1 --selector=tekton.dev/pipelineRun=$CI_COMMIT_SHA --all-containers -f --max-log-requests=8
