image: registry.gitlab.com/jonashackt/aws-kubectl-tkn:0.21.0

before_script:
  - mkdir ~/.kube
  - echo "$EKSKUBECONFIG" > ~/.kube/config
  - echo "--- Testdrive connection to cluster"
  - kubectl cluster-info
  - kubectl get nodes
  - echo "--- Test if Tekton pipelines are set up"
  - kubectl get pods --namespace tekton-pipelines
  - echo "--- Change permission for kubecfg"
  - chmod +x kubecfg

stages:
  - tkn-build

build-image:
  stage: tkn-build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    # - echo "--- Deploy nusfriends1 via kubecfg directly (without Tekton)"
    # - ./kubecfg update nusfriends1.jsonnet

    - echo "--- Create parameterized Tekton PipelineRun (using JSONNET)"
    - ./kubecfg update test_pipeline.jsonnet

    - echo "--- Show Tekton PipelineRun logs"
    - kubectl logs --selector=tekton.dev/pipelineRun=test-run-run --all-containers -f --max-log-requests=8