image: registry.gitlab.com/jonashackt/aws-kubectl-tkn:0.21.0

before_script:
  - mkdir ~/.kube
  - echo "$EKSKUBECONFIG" > ~/.kube/config
  - echo "--- Testdrive connection to cluster"
  - kubectl get nodes

stages:
  - tkn-build

build-image:
  stage: tkn-build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - echo "--- Create parameterized Tekton PipelineRun yaml"
    - echo "tkn pipeline start buildpacks-test-pipeline"

    - echo "--- Trigger PipelineRun in Tekton / K8s"
    - echo "PIPELINE_RUN_NAME=$(kubectl create -f pipelinerun.yml --output=jsonpath='{.metadata.name}')""

    - echo "--- Show Tekton PipelineRun logs"
    - echo "tkn pipelinerun logs $PIPELINE_RUN_NAME --follow"
